In [1]:
import cv2

read and Show image

In [2]:
img  = cv2.imread("image/cat1.jpg")
cv2.imshow("cat",img)
cv2.waitKey(10000)
cv2.destroyAllWindows()
# cv2.destroyWindow()  // destroy only one window

wait and destroyWindow

In [3]:
img1  = cv2.imread("image/cat1.jpg")
cv2.imshow("cat1",img1)
cv2.imshow("cat2",img1)
cv2.waitKey(10000)
cv2.destroyAllWindows()

In [4]:
import cv2
import numpy as np

Resizing Image

In [5]:
img = cv2.imread("image/cat3.jpg")
re_img = cv2.resize(img,(500,300))
cv2.imshow("cat2",re_img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [6]:
img = cv2.imread("image/cat3.jpg")
print(img)

[[[  5  37  32]
  [  4  42  36]
  [ 25  77  70]
  ...
  [ 51 162 158]
  [ 50 161 157]
  [ 49 160 156]]

 [[  5  31  25]
  [  3  37  30]
  [  3  50  42]
  ...
  [ 52 163 159]
  [ 52 163 159]
  [ 53 164 160]]

 [[  5  21  14]
  [  5  28  20]
  [  6  40  33]
  ...
  [ 52 163 159]
  [ 54 165 161]
  [ 56 167 163]]

 ...

 [[  0  42  19]
  [  0  47  23]
  [  0  51  28]
  ...
  [  5  92  82]
  [  9  96  86]
  [  7  94  84]]

 [[  3  46  25]
  [  4  51  29]
  [  0  53  30]
  ...
  [  4  91  81]
  [  7  94  84]
  [  6  93  83]]

 [[  2  47  28]
  [  5  51  32]
  [  0  53  33]
  ...
  [  4  90  80]
  [  8  94  84]
  [  8  94  84]]]


two  image show in horizontol in Single frame

In [7]:
img = cv2.imread("image/cat3.jpg")
re_img = cv2.resize(img,(300,500))
h = np.hstack((re_img,re_img))
cv2.imshow("cat", h)
cv2.waitKey(0)
cv2.destroyAllWindows()

two  image show in vertical in Single frame

In [8]:
img = cv2.imread("image/cat3.jpg")
re_img = cv2.resize(img,(300,500))
h = np.vstack((re_img,re_img))
cv2.imshow("cat", h)
cv2.waitKey(0)
cv2.destroyAllWindows()

four image show  in Single frame

In [9]:
img = cv2.imread("image/cat3.jpg")
re_img = cv2.resize(img,(300,500))
h = np.hstack((re_img,re_img))
v = np.vstack((h,h))
cv2.imshow("cat", v)
cv2.waitKey(0)
cv2.destroyAllWindows()

Six image show in single frame

In [10]:
img = cv2.imread("image/cat3.jpg")
re_img = cv2.resize(img,(300,500))
h = np.hstack((re_img,re_img,re_img))
v = np.vstack((h,h,h))
cv2.imshow("cat", v)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
import os

In [12]:
list_name = os.listdir("image")
list_name

['cat1.jpg',
 'cat2.jpeg',
 'cat3.jpg',
 'dog1.jpeg',
 'dog2.jpeg',
 'dog3.jpg',
 'dog4.jpg']

Slide show 

In [14]:
for name in list_name:
  path = "image"
  img_name = path + "\\" + name
  img = cv2.imread(img_name)
  img = cv2.resize(img,(300,500))
  cv2.imshow("cat", img)
  cv2.waitKey(1000)
cv2.destroyAllWindows()

In [15]:
for name in list_name:
  path = "image"
  img_name = path + "\\" + name
  img = cv2.imread(img_name)
  img = cv2.resize(img,(300,500))
  cv2.imshow("cat", img)
  cv2.waitKey(0)
cv2.destroyAllWindows()